### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by trhubwork** [jay3dec/PythonFlaskMySQLApp---Part-1#3]
I get the following error message in my terminal when I click the submit button.
- Running on http://127.0.0.1:5002/ (Press CTRL+C to quit)
  127.0.0.1 - - [29/Sep/2016 15:53:10] "GET / HTTP/1.1" 200 -
  127.0.0.1 - - [29/Sep/2016 15:53:13] "GET /showSignUp HTTP/1.1" 200 -
  127.0.0.1 - - [29/Sep/2016 15:53:14] "GET /static/css/signup.css HTTP/1.1" 200 -
  127.0.0.1 - - [29/Sep/2016 15:53:14] "GET /static/js/jquery-1.11.2.js HTTP/1.1" 200 -
  127.0.0.1 - - [29/Sep/2016 15:53:14] "GET /static/js/signUp.js HTTP/1.1" 200 -
  [2016-09-29 15:53:19,759] ERROR in app: Exception on /signUp [POST]
  Traceback (most recent call last):
  File "C:\Users\TR\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\TR\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\TR\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\TR\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask_compat.py", line 33, in reraise
    raise value
  File "C:\Users\TR\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\TR\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 54, in signUp
    cursor.close()
  UnboundLocalError: local variable 'cursor' referenced before assignment
  127.0.0.1 - - [29/Sep/2016 15:53:19] "POST /signUp HTTP/1.1" 500 -

The console in dev tools reads:

jquery-1.11.2.js:9659 

POST http://localhost:5002/signUp 500 (INTERNAL SERVER ERROR)send @ jquery-1.11.2.js:9659ajax @ jquery-1.11.2.js:9210(anonymous function) @ signUp.js:4dispatch @ jquery-1.11.2.js:4665elemData.handle @ jquery-1.11.2.js:4333

signUp.js:12 Object {readyState: 4, responseText: "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final/…ded or there is an error in the application.</p>↵", status: 500, statusText: "INTERNAL SERVER ERROR"}abort: ( statusText )always: ()complete: ()done: ()error: ()fail: ()getAllResponseHeaders: ()getResponseHeader: ( key )overrideMimeType: ( type )pipe: ( /\* fnDone, fnFail, fnProgress _/ )progress: ()promise: ( obj )readyState: 4responseText: "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">↵<title>500 Internal Server Error</title>↵<h1>Internal Server Error</h1>↵<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>↵"setRequestHeader: ( name, value )state: ()status: 500statusCode: ( map )statusText: "INTERNAL SERVER ERROR"success: ()then: ( /_ fnDone, fnFail, fnProgress */ )**proto**: Object

**Comment by lameei** [comment]
Any solutions here?

**Comment by johnkatt** [comment]
Has anyone been able to find the problem with this?

**Comment by shpiyu** [comment]
make sure you're using your own username and password in mysql's config instead of "jay" in app.py
and use flaskext.mysql instead of flask.ext.mysql
from flaskext.mysql import MySQL

**Comment by asyncze** [comment]
I'm using MAMP and fixed this problem by adding, 

app.config['MYSQL_DATABASE_PORT'] = 8889
app.config['MYSQL_UNIX_SOCKET'] = '/Applications/MAMP/tmp/mysql/mysql.sock'

in app.py.

**Comment by mathurawasirishabh** [comment]
app running fine but no change in database how to resolve this :
python app.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 296-410-667
127.0.0.1 - - [15/Jun/2017 11:00:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Jun/2017 11:00:43] "GET /showSignUp HTTP/1.1" 200 -
127.0.0.1 - - [15/Jun/2017 11:00:57] "POST /signUp HTTP/1.1" 200 -

**Comment by SanthoshAshokkumar** [comment]
app running fine but no change in database how to resolve this :
python app.py


Running on http://127.0.0.1:5000/ (Press CTRL+C to quit).

I am also having the same problem. Not sure, whether the python code was able to connect to MySQL. 
I tried with changing the user id & password, it still runs. 


app.config['MYSQL_DATABASE_USER'] = '  '
app.config['MYSQL_DATABASE_PASSWORD'] = '  '

Still the code works.  Any solution for windows.

**Comment by SanthoshAshokkumar** [comment]
Try running this,

if __name__ == "__main__":
    app.run(port=3306)

**Comment by sakthi7** [comment]
hey,

i am getting the bellow ERROR, Will any one help me for fix this issue. I am struggling ...

ERROR -

[2017-12-19 04:10:57,469] ERROR in app: Exception on /signUp [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 57, in signUp
    cursor.close()
UnboundLocalError: local variable 'cursor' referenced before assignment
127.0.0.1 - - [19/Dec/2017 04:10:57] "POST /signUp HTTP/1.1" 500 -

**Comment by gnany07** [comment]
sakthi7 from the error i feel that,you did not assign the cursor variable.did you do 'cursor =conn.cursor()'.Please check
